apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels:
    app: external
spec:
  type: NodePort
  selector:
    app: external
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: external
    spec:
      containers:
      - image: fernandoruaro/python-web-demo
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 1
        name: external
        env:
        - name: SERVICE
          value: http://internal-service
        - name: PARAMETER
          value: "VERSAO 1"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: internal-service
  labels:
    app: internal
spec:
  selector:
    app: internal
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - image: fernandoruaro/python-web-demo
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 180
          timeoutSeconds: 1
        name: internal
        env:
        - name: PARAMETER
          value: "VERSAO 1"
        ports:
        - containerPort: 8080
